site_name: My Docs

nav:
    - Home ğŸ : index.md
    - Practices ğŸ“š:
        - SOLID Principles ğŸª¨: solid.md

theme:
  name: material
  logo: assets/logo.png
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
